#! /bin/sh
# slc, a SVP generic compiler.
# Copyright (C) 2009,2010,2011,2012 The CSA group, The SL project.

set -e

if [ "$#" -eq "1" ]; then
  AUTORECONF=$1
  echo "Using \`$1' instead of \`autoreconf' command"
else
  AUTORECONF=autoreconf
fi

slc/build-aux/sl-init-autoconf tests/build-aux
(cd tests && ./build-aux/mkalltests.sh)
$AUTORECONF -v -f -i

echo "Reconfiguration done."
