#! /bin/sh
# slc, a SVP generic compiler.
# Copyright (C) 2009,2010 The CSA group, The SL project.

set -e

echo "Detecting which Autotools to use..."
# Some systems ship both the latest Automake and
# an older version, and default to the older. Try
# to detect this.
automake-1.11 --version >/dev/null 2>/dev/null \
  && export AUTOMAKE=automake-1.11 \
  && export ACLOCAL=aclocal-1.11

if [ "$#" -eq "1" ]; then
  AUTORECONF=$1
  echo "Using \`$1' instead of \`autoreconf' command"
else
  AUTORECONF=autoreconf
fi

slc/build-aux/sl-init-autoconf tests/build-aux
slc/build-aux/sl-init-autoconf programs/build-aux
(cd deploy/installer && cp -vf ../../slc/build-aux/{version.mk,version-gen} ./build-aux/)
(cd tests && ./build-aux/mkalltests.sh)
(cd programs/benchmarks/livermore && python ./ll-generate.py <ll-bounds.csv)
(cd programs/benchmarks/blas && ./gendata.sh)
$AUTORECONF -v -f -i

echo "Reconfiguration done."
