# This file was generated by decode.py. Do not edit!
# For each instruction the information available is:'
# re_parser, input_regs, output_regs, double_regs, long_latency, delayed, extra_phy_inputs, extra_phy_outputs'
import re
class insn_metadata(object):
    def __init__(self, info):
        self.inputs, self.outputs, self.double_regs, self.long_latency, self.delayed, self.extra_inputs, self.extra_outputs, self.immediates, self.is_branch, self.is_condbranch = info

reg = r"""(\$[lgsd]?f?\d+)"""
imm = r"""([^%$]\w*|%(?:(?:hi|lo)x?|hh|hm|lm|h44|m44|uhi|ulo|(?:tgd|tldm|tie)_(?:hi22|lo10)|(?:tldo|tle)_(?:hix22|lox10))\([^)]+\))"""
re000 = re.compile(r'''\s*''' + imm + r'''\s*$''')
re001 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*$''')
re002 = re.compile(r'''\s*$''')
re003 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + imm + r'''\s*,\s*''' + reg + r'''\s*$''')
re004 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*#asi\S*\s*,\s*''' + reg + r'''\s*$''')
re005 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*\]\s*#asi\S*\s*,\s*''' + reg + r'''\s*$''')
re006 = re.compile(r'''\s*(?:)\s*''' + imm + r'''\s*,\s*''' + reg + r'''\s*$''')
re007 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*,\s*''' + reg + r'''\s*$''')
re008 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*\]\s*,\s*''' + reg + r'''\s*$''')
re009 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*,\s*''' + reg + r'''\s*$''')
re010 = re.compile(r'''\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*,\s*''' + reg + r'''\s*$''')
re011 = re.compile(r'''\s*\[\s*''' + imm + r'''\s*\]\s*,\s*''' + reg + r'''\s*$''')
re012 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*,\s*%c\d+\S*\s*$''')
re013 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*\]\s*,\s*%c\d+\S*\s*$''')
re014 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*,\s*%c\d+\S*\s*$''')
re015 = re.compile(r'''\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*,\s*%c\d+\S*\s*$''')
re016 = re.compile(r'''\s*\[\s*''' + imm + r'''\s*\]\s*,\s*%c\d+\S*\s*$''')
re017 = re.compile(r'''\s*''' + imm + r'''\s*,\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*$''')
re018 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*$''')
re019 = re.compile(r'''\s*''' + imm + r'''\s*,\s*''' + reg + r'''\s*$''')
re020 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*,\s*%fsr\S*\s*$''')
re021 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*\]\s*,\s*%fsr\S*\s*$''')
re022 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*,\s*%fsr\S*\s*$''')
re023 = re.compile(r'''\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*,\s*%fsr\S*\s*$''')
re024 = re.compile(r'''\s*\[\s*''' + imm + r'''\s*\]\s*,\s*%fsr\S*\s*$''')
re025 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*,\s*%csr\S*\s*$''')
re026 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*\]\s*,\s*%csr\S*\s*$''')
re027 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*,\s*%csr\S*\s*$''')
re028 = re.compile(r'''\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*,\s*%csr\S*\s*$''')
re029 = re.compile(r'''\s*\[\s*''' + imm + r'''\s*\]\s*,\s*%csr\S*\s*$''')
re030 = re.compile(r'''\s*''' + reg + r'''\s*$''')
re031 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + imm + r'''\s*$''')
re032 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*,\s*%asr\S*\s*$''')
re033 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + imm + r'''\s*,\s*%asr\S*\s*$''')
re034 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*,\s*%y\S*\s*$''')
re035 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + imm + r'''\s*,\s*%y\S*\s*$''')
re036 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*,\s*%psr\S*\s*$''')
re037 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + imm + r'''\s*,\s*%psr\S*\s*$''')
re038 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*,\s*%wim\S*\s*$''')
re039 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + imm + r'''\s*,\s*%wim\S*\s*$''')
re040 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*,\s*%tbr\S*\s*$''')
re041 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + imm + r'''\s*,\s*%tbr\S*\s*$''')
re042 = re.compile(r'''\s*%asr\d+\S*\s*,\s*''' + reg + r'''\s*$''')
re043 = re.compile(r'''\s*%y\S*\s*,\s*''' + reg + r'''\s*$''')
re044 = re.compile(r'''\s*%psr\S*\s*,\s*''' + reg + r'''\s*$''')
re045 = re.compile(r'''\s*%wim\S*\s*,\s*''' + reg + r'''\s*$''')
re046 = re.compile(r'''\s*%tbr\S*\s*,\s*''' + reg + r'''\s*$''')
re047 = re.compile(r'''\s*''' + reg + r'''\s*,\s*%asr\S*\s*$''')
re048 = re.compile(r'''\s*''' + imm + r'''\s*,\s*%asr\S*\s*$''')
re049 = re.compile(r'''\s*''' + reg + r'''\s*,\s*%y\S*\s*$''')
re050 = re.compile(r'''\s*''' + imm + r'''\s*,\s*%y\S*\s*$''')
re051 = re.compile(r'''\s*''' + reg + r'''\s*,\s*%psr\S*\s*$''')
re052 = re.compile(r'''\s*''' + imm + r'''\s*,\s*%psr\S*\s*$''')
re053 = re.compile(r'''\s*''' + reg + r'''\s*,\s*%wim\S*\s*$''')
re054 = re.compile(r'''\s*''' + imm + r'''\s*,\s*%wim\S*\s*$''')
re055 = re.compile(r'''\s*''' + reg + r'''\s*,\s*%tbr\S*\s*$''')
re056 = re.compile(r'''\s*''' + imm + r'''\s*,\s*%tbr\S*\s*$''')
re057 = re.compile(r'''\s*''' + reg + r'''\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re058 = re.compile(r'''\s*''' + reg + r'''\s*,\s*\[\s*''' + reg + r'''\s*\]\s*$''')
re059 = re.compile(r'''\s*''' + reg + r'''\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*$''')
re060 = re.compile(r'''\s*''' + reg + r'''\s*,\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re061 = re.compile(r'''\s*''' + reg + r'''\s*,\s*\[\s*''' + imm + r'''\s*\]\s*$''')
re062 = re.compile(r'''\s*%c\d+\S*\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re063 = re.compile(r'''\s*%c\d+\S*\s*,\s*\[\s*''' + reg + r'''\s*\]\s*$''')
re064 = re.compile(r'''\s*%c\d+\S*\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*$''')
re065 = re.compile(r'''\s*%c\d+\S*\s*,\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re066 = re.compile(r'''\s*%c\d+\S*\s*,\s*\[\s*''' + imm + r'''\s*\]\s*$''')
re067 = re.compile(r'''\s*%csr\S*\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re068 = re.compile(r'''\s*%csr\S*\s*,\s*\[\s*''' + reg + r'''\s*\]\s*$''')
re069 = re.compile(r'''\s*%csr\S*\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*$''')
re070 = re.compile(r'''\s*%csr\S*\s*,\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re071 = re.compile(r'''\s*%csr\S*\s*,\s*\[\s*''' + imm + r'''\s*\]\s*$''')
re072 = re.compile(r'''\s*%fsr\S*\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re073 = re.compile(r'''\s*%fsr\S*\s*,\s*\[\s*''' + reg + r'''\s*\]\s*$''')
re074 = re.compile(r'''\s*%fsr\S*\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*$''')
re075 = re.compile(r'''\s*%fsr\S*\s*,\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re076 = re.compile(r'''\s*%fsr\S*\s*,\s*\[\s*''' + imm + r'''\s*\]\s*$''')
re077 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re078 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*\]\s*$''')
re079 = re.compile(r'''\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*$''')
re080 = re.compile(r'''\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re081 = re.compile(r'''\s*\[\s*''' + imm + r'''\s*\]\s*$''')
re082 = re.compile(r'''\s*''' + reg + r'''\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*#asi\S*\s*$''')
re083 = re.compile(r'''\s*''' + reg + r'''\s*,\s*\[\s*''' + reg + r'''\s*\]\s*#asi\S*\s*$''')
re084 = re.compile(r'''\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*$''')
re085 = re.compile(r'''\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*,\s*''' + reg + r'''\s*$''')
re086 = re.compile(r'''\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*$''')
re087 = re.compile(r'''\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*$''')
re088 = re.compile(r'''\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*$''')
re089 = re.compile(r'''\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*$''')
re090 = re.compile(r'''\s*''' + reg + r'''\s*,\s*''' + reg + r'''\s*,\s*''' + imm + r'''\s*$''')
re091 = re.compile(r'''\s*''' + imm + r'''\s*,\s*\d+\s*$''')
re092 = re.compile(r'''\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*,\s*\d+\s*$''')
re093 = re.compile(r'''\s*''' + reg + r'''\s*,\s*\d+\s*$''')
re094 = re.compile(r'''\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*,\s*\d+\s*$''')
re095 = re.compile(r'''\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*,\s*\d+\s*$''')
re096 = re.compile(r'''\s*%fq\S*\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re097 = re.compile(r'''\s*%fq\S*\s*,\s*\[\s*''' + reg + r'''\s*\]\s*$''')
re098 = re.compile(r'''\s*%fq\S*\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*$''')
re099 = re.compile(r'''\s*%fq\S*\s*,\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re100 = re.compile(r'''\s*%fq\S*\s*,\s*\[\s*''' + imm + r'''\s*\]\s*$''')
re101 = re.compile(r'''\s*%cq\S*\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re102 = re.compile(r'''\s*%cq\S*\s*,\s*\[\s*''' + reg + r'''\s*\]\s*$''')
re103 = re.compile(r'''\s*%cq\S*\s*,\s*\[\s*''' + reg + r'''\s*[+-]\s*''' + imm + r'''\s*\]\s*$''')
re104 = re.compile(r'''\s*%cq\S*\s*,\s*\[\s*''' + imm + r'''\s*[+-]\s*''' + reg + r'''\s*\]\s*$''')
re105 = re.compile(r'''\s*%cq\S*\s*,\s*\[\s*''' + imm + r'''\s*\]\s*$''')
form000 = insn_metadata(([], [], [], False, True, [], [], [0], False, True))
form001 = insn_metadata(([0, 1], [2], [], False, False, [], [], [], False, False))
form002 = insn_metadata(([], [], [], False, False, [], [], [], False, False))
form003 = insn_metadata(([0], [2], [], False, False, [], [], [1], False, False))
form004 = insn_metadata(([0, 1], [2], [], True, False, [], [], [], False, False))
form005 = insn_metadata(([0], [1], [], True, False, [], [], [], False, False))
form006 = insn_metadata(([], [1], [], False, False, [], [], [0], False, False))
form007 = insn_metadata(([0, 1], [2], [2], True, False, [], [], [], False, False))
form008 = insn_metadata(([0], [1], [1], True, False, [], [], [], False, False))
form009 = insn_metadata(([0], [2], [2], True, False, [], [], [1], False, False))
form010 = insn_metadata(([1], [2], [2], True, False, [], [], [0], False, False))
form011 = insn_metadata(([], [1], [1], True, False, [], [], [0], False, False))
form012 = insn_metadata(([0, 1], [], [], True, False, [], [], [], False, False))
form013 = insn_metadata(([0], [], [], True, False, [], [], [], False, False))
form014 = insn_metadata(([0], [], [], True, False, [], [], [1], False, False))
form015 = insn_metadata(([1], [], [], True, False, [], [], [0], False, False))
form016 = insn_metadata(([], [], [], True, False, [], [], [0], False, False))
form017 = insn_metadata(([1], [2], [], False, False, [], [], [0], False, False))
form018 = insn_metadata(([0, 1], [], [], False, False, [], [], [], False, False))
form019 = insn_metadata(([0, 1], [1], [], False, False, [], [], [], False, False))
form020 = insn_metadata(([1], [1], [], False, False, [], [], [0], False, False))
form021 = insn_metadata(([0], [2], [], True, False, [], [], [1], False, False))
form022 = insn_metadata(([1], [2], [], True, False, [], [], [0], False, False))
form023 = insn_metadata(([], [1], [], True, False, [], [], [0], False, False))
form024 = insn_metadata(([0], [], [], False, False, [], [], [], False, False))
form025 = insn_metadata(([], [0], [], True, False, [], [], [], False, False))
form026 = insn_metadata(([0], [], [], False, False, [], [], [1], False, False))
form027 = insn_metadata(([], [0], [], False, False, [], [], [], False, False))
form028 = insn_metadata(([], [], [], False, False, [], [], [0], False, False))
form029 = insn_metadata(([0], [1], [], False, False, [], [], [], False, False))
form030 = insn_metadata(([0, 1], [2], [], True, False, [], ['y'], [], False, False))
form031 = insn_metadata(([0], [2], [], True, False, [], ['y'], [1], False, False))
form032 = insn_metadata(([1], [2], [], True, False, [], ['y'], [0], False, False))
form033 = insn_metadata(([0, 1, 2], [], [], False, False, [], [], [], False, False))
form034 = insn_metadata(([0, 1], [], [], False, False, [], [], [2], False, False))
form035 = insn_metadata(([0, 2], [], [], False, False, [], [], [1], False, False))
form036 = insn_metadata(([1], [], [], False, False, [], [], [0], False, False))
form037 = insn_metadata(([0], [0], [], False, False, [], [], [], False, False))
form038 = insn_metadata(([0, 1], [2], [], True, False, ['y'], [], [], False, False))
form039 = insn_metadata(([0], [2], [], True, False, ['y'], [], [1], False, False))
form040 = insn_metadata(([1], [2], [], True, False, ['y'], [], [0], False, False))
form041 = insn_metadata(([0, 1], [2], [], False, True, [], [], [], True, False))
form042 = insn_metadata(([0], [1], [], False, True, [], [], [], True, False))
form043 = insn_metadata(([], [1], [], False, True, [], [], [0], True, False))
form044 = insn_metadata(([0], [2], [], False, True, [], [], [1], True, False))
form045 = insn_metadata(([1], [2], [], False, True, [], [], [0], True, False))
form046 = insn_metadata(([], [], [], False, True, [], [], [0], True, False))
form047 = insn_metadata(([0, 1, 2], [], [0], False, False, [], [], [], False, False))
form048 = insn_metadata(([0, 1], [], [0], False, False, [], [], [], False, False))
form049 = insn_metadata(([], [], [], False, True, [15], [], [], True, False))
form050 = insn_metadata(([], [], [], True, False, [], [], [], False, False))
form051 = insn_metadata(([], [], [], False, True, [31], [], [], True, False))
form052 = insn_metadata(([], [], [], False, True, [], [15], [0], True, False))
form053 = insn_metadata(([0, 1], [], [], False, True, [], [15], [], True, False))
form054 = insn_metadata(([0], [], [], False, True, [], [15], [], True, False))
form055 = insn_metadata(([0], [], [], False, True, [], [15], [1], True, False))
form056 = insn_metadata(([1], [], [], False, True, [], [15], [0], True, False))
form057 = insn_metadata(([0, 1], [], [], False, True, [], [], [], True, False))
form058 = insn_metadata(([0], [], [], False, True, [], [], [], True, False))
form059 = insn_metadata(([0], [], [], False, True, [], [], [1], True, False))
form060 = insn_metadata(([1], [], [], False, True, [], [], [0], True, False))
form061 = insn_metadata(([0, 1], [], [0], False, False, [], [], [2], False, False))
form062 = insn_metadata(([0, 2], [], [0], False, False, [], [], [1], False, False))
form063 = insn_metadata(([0], [], [0], False, False, [], [], [1], False, False))
form064 = insn_metadata(([0], [], [], False, False, [], [], [], True, False))
insninfo = {
'add' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'addcc' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'addx' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'addxcc' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'allocate' : [
      (re030, form025),
      (re018, form005),
      (re019, form023),
      ],
'allocates' : [
      (re030, form025),
      (re018, form005),
      (re019, form023),
      ],
'allocatex' : [
      (re030, form025),
      (re018, form005),
      (re019, form023),
      ],
'and' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'andcc' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'andn' : [
      (re001, form001),
      (re003, form003),
      ],
'andncc' : [
      (re001, form001),
      (re003, form003),
      ],
'b' : [
      (re000, form046),
      ],
'b,a' : [
      (re000, form046),
      ],
'ba' : [
      (re000, form000),
      ],
'ba,a' : [
      (re000, form000),
      ],
'bcc' : [
      (re000, form000),
      ],
'bcc,a' : [
      (re000, form000),
      ],
'bclr' : [
      (re018, form019),
      (re019, form020),
      ],
'bcs' : [
      (re000, form000),
      ],
'bcs,a' : [
      (re000, form000),
      ],
'be' : [
      (re000, form000),
      ],
'be,a' : [
      (re000, form000),
      ],
'beq' : [
      (re000, form000),
      ],
'beq,a' : [
      (re000, form000),
      ],
'bg' : [
      (re000, form000),
      ],
'bg,a' : [
      (re000, form000),
      ],
'bge' : [
      (re000, form000),
      ],
'bge,a' : [
      (re000, form000),
      ],
'bgeu' : [
      (re000, form000),
      ],
'bgeu,a' : [
      (re000, form000),
      ],
'bgt' : [
      (re000, form000),
      ],
'bgt,a' : [
      (re000, form000),
      ],
'bgu' : [
      (re000, form000),
      ],
'bgu,a' : [
      (re000, form000),
      ],
'bl' : [
      (re000, form000),
      ],
'bl,a' : [
      (re000, form000),
      ],
'ble' : [
      (re000, form000),
      ],
'ble,a' : [
      (re000, form000),
      ],
'bleu' : [
      (re000, form000),
      ],
'bleu,a' : [
      (re000, form000),
      ],
'blt' : [
      (re000, form000),
      ],
'blt,a' : [
      (re000, form000),
      ],
'blu' : [
      (re000, form000),
      ],
'blu,a' : [
      (re000, form000),
      ],
'bn' : [
      (re000, form000),
      ],
'bn,a' : [
      (re000, form000),
      ],
'bne' : [
      (re000, form000),
      ],
'bne,a' : [
      (re000, form000),
      ],
'bneg' : [
      (re000, form000),
      ],
'bneg,a' : [
      (re000, form000),
      ],
'bnz' : [
      (re000, form000),
      ],
'bnz,a' : [
      (re000, form000),
      ],
'bpos' : [
      (re000, form000),
      ],
'bpos,a' : [
      (re000, form000),
      ],
'break' : [
      (re030, form024),
      (re000, form028),
      ],
'bset' : [
      (re018, form019),
      (re019, form020),
      ],
'btog' : [
      (re018, form019),
      (re019, form020),
      ],
'btst' : [
      (re018, form018),
      (re019, form036),
      ],
'bvc' : [
      (re000, form000),
      ],
'bvc,a' : [
      (re000, form000),
      ],
'bvs' : [
      (re000, form000),
      ],
'bvs,a' : [
      (re000, form000),
      ],
'bz' : [
      (re000, form000),
      ],
'bz,a' : [
      (re000, form000),
      ],
'call' : [
      (re000, form052),
      (re091, form052),
      (re087, form053),
      (re092, form053),
      (re030, form054),
      (re093, form054),
      (re088, form055),
      (re094, form055),
      (re089, form056),
      (re095, form056),
      (re000, form052),
      (re091, form052),
      (re030, form054),
      (re093, form054),
      ],
'clr' : [
      (re030, form027),
      (re030, form027),
      (re077, form018),
      (re078, form024),
      (re079, form026),
      (re080, form036),
      (re081, form028),
      (re078, form024),
      ],
'clrb' : [
      (re077, form018),
      (re078, form024),
      (re079, form026),
      (re080, form036),
      (re081, form028),
      (re078, form024),
      ],
'clrh' : [
      (re077, form018),
      (re078, form024),
      (re079, form026),
      (re080, form036),
      (re081, form028),
      (re078, form024),
      ],
'cmp' : [
      (re018, form018),
      (re031, form026),
      ],
'cpop1' : [
      (re007, form001),
      ],
'cpop2' : [
      (re007, form001),
      ],
'create' : [
      (re018, form005),
      ],
'cred' : [
      (re019, form015),
      ],
'crei' : [
      (re018, form012),
      ],
'dec' : [
      (re030, form037),
      (re019, form020),
      ],
'deccc' : [
      (re030, form037),
      (re019, form020),
      ],
'detach' : [
      (re030, form024),
      ],
'fabss' : [
      (re018, form029),
      ],
'faddd' : [
      (re001, form004),
      ],
'faddq' : [
      (re001, form004),
      ],
'fadds' : [
      (re001, form004),
      ],
'faddx' : [
      (re001, form004),
      ],
'fb' : [
      (re000, form000),
      ],
'fb,a' : [
      (re000, form000),
      ],
'fba' : [
      (re000, form000),
      ],
'fba,a' : [
      (re000, form000),
      ],
'fbe' : [
      (re000, form000),
      ],
'fbe,a' : [
      (re000, form000),
      ],
'fbg' : [
      (re000, form000),
      ],
'fbg,a' : [
      (re000, form000),
      ],
'fbge' : [
      (re000, form000),
      ],
'fbge,a' : [
      (re000, form000),
      ],
'fbl' : [
      (re000, form000),
      ],
'fbl,a' : [
      (re000, form000),
      ],
'fble' : [
      (re000, form000),
      ],
'fble,a' : [
      (re000, form000),
      ],
'fblg' : [
      (re000, form000),
      ],
'fblg,a' : [
      (re000, form000),
      ],
'fbn' : [
      (re000, form000),
      ],
'fbn,a' : [
      (re000, form000),
      ],
'fbne' : [
      (re000, form000),
      ],
'fbne,a' : [
      (re000, form000),
      ],
'fbnz' : [
      (re000, form000),
      ],
'fbnz,a' : [
      (re000, form000),
      ],
'fbo' : [
      (re000, form000),
      ],
'fbo,a' : [
      (re000, form000),
      ],
'fbu' : [
      (re000, form000),
      ],
'fbu,a' : [
      (re000, form000),
      ],
'fbue' : [
      (re000, form000),
      ],
'fbue,a' : [
      (re000, form000),
      ],
'fbug' : [
      (re000, form000),
      ],
'fbug,a' : [
      (re000, form000),
      ],
'fbuge' : [
      (re000, form000),
      ],
'fbuge,a' : [
      (re000, form000),
      ],
'fbul' : [
      (re000, form000),
      ],
'fbul,a' : [
      (re000, form000),
      ],
'fbule' : [
      (re000, form000),
      ],
'fbule,a' : [
      (re000, form000),
      ],
'fbz' : [
      (re000, form000),
      ],
'fbz,a' : [
      (re000, form000),
      ],
'fcmpd' : [
      (re018, form012),
      ],
'fcmped' : [
      (re018, form012),
      ],
'fcmpeq' : [
      (re018, form012),
      ],
'fcmpes' : [
      (re018, form012),
      ],
'fcmpex' : [
      (re018, form012),
      ],
'fcmpq' : [
      (re018, form012),
      ],
'fcmps' : [
      (re018, form012),
      ],
'fcmpx' : [
      (re018, form012),
      ],
'fdivd' : [
      (re001, form004),
      ],
'fdivq' : [
      (re001, form004),
      ],
'fdivs' : [
      (re001, form004),
      ],
'fdivx' : [
      (re001, form004),
      ],
'fdmulq' : [
      (re001, form004),
      ],
'fdmulx' : [
      (re001, form004),
      ],
'fdtoi' : [
      (re018, form029),
      ],
'fdtoq' : [
      (re018, form029),
      ],
'fdtos' : [
      (re018, form029),
      ],
'fgets' : [
      (re003, form021),
      ],
'fitod' : [
      (re018, form029),
      ],
'fitoq' : [
      (re018, form029),
      ],
'fitos' : [
      (re018, form029),
      ],
'flush' : [
      (re087, form012),
      (re030, form013),
      (re030, form013),
      (re000, form016),
      (re088, form014),
      (re089, form015),
      ],
'fmovs' : [
      (re018, form029),
      ],
'fmuld' : [
      (re001, form004),
      ],
'fmulq' : [
      (re001, form004),
      ],
'fmuls' : [
      (re001, form004),
      ],
'fmulx' : [
      (re001, form004),
      ],
'fnegs' : [
      (re018, form029),
      ],
'fprintd' : [
      (re018, form018),
      ],
'fprintq' : [
      (re018, form018),
      ],
'fprints' : [
      (re018, form018),
      ],
'fputg' : [
      (re090, form034),
      ],
'fputs' : [
      (re090, form034),
      ],
'fqtod' : [
      (re018, form029),
      ],
'fqtoi' : [
      (re018, form029),
      ],
'fqtos' : [
      (re018, form029),
      ],
'fsmuld' : [
      (re001, form004),
      ],
'fsqrtd' : [
      (re018, form005),
      ],
'fsqrtq' : [
      (re018, form005),
      ],
'fsqrts' : [
      (re018, form005),
      ],
'fsqrtx' : [
      (re018, form005),
      ],
'fstod' : [
      (re018, form029),
      ],
'fstoi' : [
      (re018, form029),
      ],
'fstoq' : [
      (re018, form029),
      ],
'fsubd' : [
      (re001, form004),
      ],
'fsubq' : [
      (re001, form004),
      ],
'fsubs' : [
      (re001, form004),
      ],
'fsubx' : [
      (re001, form004),
      ],
'getcid' : [
      (re030, form027),
      ],
'getfid' : [
      (re030, form027),
      ],
'getpid' : [
      (re030, form027),
      ],
'gets' : [
      (re003, form021),
      ],
'gettid' : [
      (re030, form027),
      ],
'iflush' : [
      (re087, form012),
      (re030, form013),
      (re030, form013),
      (re000, form016),
      (re088, form014),
      (re089, form015),
      ],
'inc' : [
      (re030, form037),
      (re019, form020),
      ],
'inccc' : [
      (re030, form037),
      (re019, form020),
      ],
'jmp' : [
      (re087, form057),
      (re030, form058),
      (re088, form059),
      (re089, form060),
      (re000, form046),
      (re030, form058),
      ],
'jmpl' : [
      (re084, form041),
      (re018, form042),
      (re018, form042),
      (re019, form043),
      (re085, form044),
      (re086, form045),
      ],
'launch' : [
      (re030, form064),
      ],
'ld' : [
      (re007, form004),
      (re008, form005),
      (re009, form021),
      (re010, form022),
      (re011, form023),
      (re008, form005),
      (re007, form004),
      (re008, form005),
      (re009, form021),
      (re010, form022),
      (re011, form023),
      (re008, form005),
      (re020, form012),
      (re021, form013),
      (re022, form014),
      (re023, form015),
      (re024, form016),
      (re021, form013),
      (re012, form012),
      (re013, form013),
      (re014, form014),
      (re015, form015),
      (re016, form016),
      (re013, form013),
      (re025, form012),
      (re026, form013),
      (re027, form014),
      (re028, form015),
      (re029, form016),
      (re026, form013),
      ],
'lda' : [
      (re004, form004),
      (re005, form005),
      ],
'ldbp' : [
      (re030, form027),
      ],
'ldd' : [
      (re007, form007),
      (re008, form008),
      (re009, form009),
      (re010, form010),
      (re011, form011),
      (re008, form008),
      (re007, form007),
      (re008, form008),
      (re009, form009),
      (re010, form010),
      (re011, form011),
      (re008, form008),
      (re012, form012),
      (re013, form013),
      (re014, form014),
      (re015, form015),
      (re016, form016),
      (re013, form013),
      ],
'ldda' : [
      (re004, form004),
      (re005, form005),
      ],
'ldfp' : [
      (re030, form027),
      ],
'ldsb' : [
      (re007, form004),
      (re008, form005),
      (re009, form021),
      (re010, form022),
      (re011, form023),
      (re008, form005),
      ],
'ldsba' : [
      (re004, form004),
      (re005, form005),
      ],
'ldsh' : [
      (re008, form005),
      (re007, form004),
      (re009, form021),
      (re010, form022),
      (re011, form023),
      (re008, form005),
      ],
'ldsha' : [
      (re004, form004),
      (re005, form005),
      ],
'ldstub' : [
      (re007, form004),
      (re008, form005),
      (re009, form021),
      (re010, form022),
      (re011, form023),
      (re008, form005),
      ],
'ldstuba' : [
      (re004, form004),
      (re005, form005),
      ],
'ldub' : [
      (re007, form004),
      (re008, form005),
      (re009, form021),
      (re010, form022),
      (re011, form023),
      (re008, form005),
      ],
'lduba' : [
      (re004, form004),
      (re005, form005),
      ],
'lduh' : [
      (re007, form004),
      (re008, form005),
      (re009, form021),
      (re010, form022),
      (re011, form023),
      (re008, form005),
      ],
'lduha' : [
      (re004, form004),
      (re005, form005),
      ],
'mov' : [
      (re032, form018),
      (re033, form026),
      (re034, form018),
      (re035, form026),
      (re036, form018),
      (re037, form026),
      (re038, form018),
      (re039, form026),
      (re040, form018),
      (re041, form026),
      (re042, form027),
      (re043, form027),
      (re044, form027),
      (re045, form027),
      (re046, form027),
      (re047, form024),
      (re048, form028),
      (re047, form024),
      (re049, form024),
      (re050, form028),
      (re049, form024),
      (re051, form024),
      (re052, form028),
      (re051, form024),
      (re053, form024),
      (re054, form028),
      (re053, form024),
      (re055, form024),
      (re056, form028),
      (re055, form024),
      (re018, form029),
      (re019, form006),
      (re018, form029),
      (re018, form029),
      ],
'mulscc' : [
      (re001, form038),
      (re003, form039),
      ],
'neg' : [
      (re018, form029),
      (re030, form037),
      ],
'nop' : [
      (re002, form002),
      ],
'not' : [
      (re018, form029),
      (re030, form037),
      ],
'or' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'orcc' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'orn' : [
      (re001, form001),
      (re003, form003),
      ],
'orncc' : [
      (re001, form001),
      (re003, form003),
      ],
'print' : [
      (re018, form018),
      (re031, form026),
      ],
'putg' : [
      (re090, form034),
      ],
'puts' : [
      (re090, form034),
      ],
'rd' : [
      (re042, form027),
      (re043, form027),
      (re044, form027),
      (re045, form027),
      (re046, form027),
      ],
'release' : [
      (re030, form024),
      ],
'restore' : [
      (re001, form001),
      (re002, form002),
      (re003, form003),
      (re002, form002),
      ],
'ret' : [
      (re002, form049),
      ],
'retl' : [
      (re002, form051),
      ],
'rett' : [
      (re087, form057),
      (re030, form058),
      (re088, form059),
      (re089, form060),
      (re000, form046),
      (re000, form046),
      (re030, form058),
      ],
'save' : [
      (re001, form001),
      (re003, form003),
      (re002, form002),
      ],
'sdiv' : [
      (re001, form038),
      (re003, form039),
      (re017, form040),
      ],
'sdivcc' : [
      (re001, form038),
      (re003, form039),
      (re017, form040),
      ],
'set' : [
      (re006, form006),
      ],
'setblock' : [
      (re018, form018),
      (re031, form026),
      ],
'sethi' : [
      (re019, form006),
      ],
'setlimit' : [
      (re018, form018),
      (re031, form026),
      ],
'setstart' : [
      (re018, form018),
      (re031, form026),
      ],
'setstep' : [
      (re018, form018),
      (re031, form026),
      ],
'setthread' : [
      (re018, form018),
      (re031, form026),
      ],
'sll' : [
      (re001, form001),
      (re003, form003),
      ],
'smul' : [
      (re001, form030),
      (re003, form031),
      (re017, form032),
      ],
'smulcc' : [
      (re001, form030),
      (re003, form031),
      (re017, form032),
      ],
'spill' : [
      (re057, form033),
      (re058, form018),
      (re059, form034),
      (re060, form035),
      (re061, form026),
      (re058, form018),
      ],
'spilld' : [
      (re057, form047),
      (re058, form048),
      (re059, form061),
      (re060, form062),
      (re061, form063),
      (re058, form048),
      ],
'sra' : [
      (re001, form001),
      (re003, form003),
      ],
'srl' : [
      (re001, form001),
      (re003, form003),
      ],
'st' : [
      (re057, form033),
      (re058, form018),
      (re059, form034),
      (re060, form035),
      (re061, form026),
      (re058, form018),
      (re057, form033),
      (re058, form018),
      (re059, form034),
      (re060, form035),
      (re061, form026),
      (re058, form018),
      (re062, form018),
      (re063, form024),
      (re064, form026),
      (re065, form036),
      (re066, form028),
      (re063, form024),
      (re067, form018),
      (re068, form024),
      (re069, form026),
      (re070, form036),
      (re071, form028),
      (re068, form024),
      (re072, form018),
      (re073, form024),
      (re074, form026),
      (re075, form036),
      (re076, form028),
      (re073, form024),
      ],
'sta' : [
      (re082, form033),
      (re083, form018),
      ],
'stb' : [
      (re057, form033),
      (re058, form018),
      (re059, form034),
      (re060, form035),
      (re061, form026),
      (re058, form018),
      ],
'stba' : [
      (re082, form033),
      (re083, form018),
      ],
'stbar' : [
      (re002, form050),
      ],
'std' : [
      (re057, form047),
      (re058, form048),
      (re059, form061),
      (re060, form062),
      (re061, form063),
      (re058, form048),
      (re096, form018),
      (re097, form024),
      (re098, form026),
      (re099, form036),
      (re100, form028),
      (re097, form024),
      (re057, form047),
      (re058, form048),
      (re059, form061),
      (re060, form062),
      (re061, form063),
      (re058, form048),
      (re101, form018),
      (re102, form024),
      (re103, form026),
      (re104, form036),
      (re105, form028),
      (re102, form024),
      (re062, form018),
      (re063, form024),
      (re064, form026),
      (re065, form036),
      (re066, form028),
      (re063, form024),
      ],
'stda' : [
      (re082, form047),
      (re083, form048),
      ],
'sth' : [
      (re057, form033),
      (re058, form018),
      (re059, form034),
      (re060, form035),
      (re061, form026),
      (re058, form018),
      ],
'stha' : [
      (re082, form033),
      (re083, form018),
      ],
'stsb' : [
      (re057, form033),
      (re058, form018),
      (re059, form034),
      (re060, form035),
      (re061, form026),
      (re058, form018),
      ],
'stsba' : [
      (re082, form033),
      (re083, form018),
      ],
'stsh' : [
      (re057, form033),
      (re058, form018),
      (re059, form034),
      (re060, form035),
      (re061, form026),
      (re058, form018),
      ],
'stsha' : [
      (re082, form033),
      (re083, form018),
      ],
'stub' : [
      (re057, form033),
      (re058, form018),
      (re059, form034),
      (re060, form035),
      (re061, form026),
      (re058, form018),
      ],
'stuba' : [
      (re082, form033),
      (re083, form018),
      ],
'stuh' : [
      (re057, form033),
      (re058, form018),
      (re059, form034),
      (re060, form035),
      (re061, form026),
      (re058, form018),
      ],
'stuha' : [
      (re082, form033),
      (re083, form018),
      ],
'sub' : [
      (re001, form001),
      (re003, form003),
      ],
'subcc' : [
      (re001, form001),
      (re003, form003),
      ],
'subx' : [
      (re001, form001),
      (re003, form003),
      ],
'subxcc' : [
      (re001, form001),
      (re003, form003),
      ],
'swap' : [
      (re007, form004),
      (re008, form005),
      (re009, form021),
      (re010, form022),
      (re011, form023),
      (re008, form005),
      ],
'swapa' : [
      (re004, form004),
      (re005, form005),
      ],
'sync' : [
      (re018, form005),
      ],
'taddcc' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'taddcctv' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'tst' : [
      (re030, form024),
      (re030, form024),
      (re030, form024),
      ],
'tsubcc' : [
      (re001, form001),
      (re003, form003),
      ],
'tsubcctv' : [
      (re001, form001),
      (re003, form003),
      ],
'udiv' : [
      (re001, form038),
      (re003, form039),
      (re017, form040),
      ],
'udivcc' : [
      (re001, form038),
      (re003, form039),
      (re017, form040),
      ],
'umul' : [
      (re001, form030),
      (re003, form031),
      (re017, form032),
      ],
'umulcc' : [
      (re001, form030),
      (re003, form031),
      (re017, form032),
      ],
'unimp' : [
      (re000, form028),
      ],
'wr' : [
      (re032, form018),
      (re033, form026),
      (re047, form024),
      (re034, form018),
      (re035, form026),
      (re049, form024),
      (re036, form018),
      (re037, form026),
      (re051, form024),
      (re038, form018),
      (re039, form026),
      (re053, form024),
      (re040, form018),
      (re041, form026),
      (re055, form024),
      ],
'xnor' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'xnorcc' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'xor' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
'xorcc' : [
      (re001, form001),
      (re003, form003),
      (re017, form017),
      ],
}
