#! /bin/sh
# slc, a SVP generic compiler.
# Copyright (C) 2009,2010,2011,2012 The CSA group, The SL project.

set -e

if [ "$#" -eq "1" ]; then
  AUTORECONF=$1
  echo "Using \`$1' instead of \`autoreconf' command"
else
  AUTORECONF=autoreconf
fi

if test -x ../slc/build-aux/sl-init-autoconf; then
   ../slc/build-aux/sl-init-autoconf
else
   sl-init-autoconf
fi

./build-aux/mkalltests.sh
$AUTORECONF -v -f -i

echo "Reconfiguration done."

