MIPSELMATHOBJS = \
  $(srcdir)/../libc/math/mipsel/acosf.o \
  $(srcdir)/../libc/math/mipsel/acoshf.o \
  $(srcdir)/../libc/math/mipsel/asinf.o \
  $(srcdir)/../libc/math/mipsel/asinhf.o \
  $(srcdir)/../libc/math/mipsel/atan2f.o \
  $(srcdir)/../libc/math/mipsel/atanf.o \
  $(srcdir)/../libc/math/mipsel/atanhf.o \
  $(srcdir)/../libc/math/mipsel/cabsf.o \
  $(srcdir)/../libc/math/mipsel/carg.o \
  $(srcdir)/../libc/math/mipsel/cargf.o \
  $(srcdir)/../libc/math/mipsel/cbrtf.o \
  $(srcdir)/../libc/math/mipsel/ceilf.o \
  $(srcdir)/../libc/math/mipsel/copysignf.o \
  $(srcdir)/../libc/math/mipsel/cosf.o \
  $(srcdir)/../libc/math/mipsel/coshf.o \
  $(srcdir)/../libc/math/mipsel/e_acos.o \
  $(srcdir)/../libc/math/mipsel/e_acosh.o \
  $(srcdir)/../libc/math/mipsel/e_asin.o \
  $(srcdir)/../libc/math/mipsel/e_atan2.o \
  $(srcdir)/../libc/math/mipsel/e_atanh.o \
  $(srcdir)/../libc/math/mipsel/e_cosh.o \
  $(srcdir)/../libc/math/mipsel/e_exp.o \
  $(srcdir)/../libc/math/mipsel/e_fmod.o \
  $(srcdir)/../libc/math/mipsel/e_gamma.o \
  $(srcdir)/../libc/math/mipsel/e_gamma_r.o \
  $(srcdir)/../libc/math/mipsel/e_hypot.o \
  $(srcdir)/../libc/math/mipsel/e_j0.o \
  $(srcdir)/../libc/math/mipsel/e_j1.o \
  $(srcdir)/../libc/math/mipsel/e_jn.o \
  $(srcdir)/../libc/math/mipsel/e_lgamma.o \
  $(srcdir)/../libc/math/mipsel/e_lgamma_r.o \
  $(srcdir)/../libc/math/mipsel/e_log.o \
  $(srcdir)/../libc/math/mipsel/e_log10.o \
  $(srcdir)/../libc/math/mipsel/e_log2.o \
  $(srcdir)/../libc/math/mipsel/e_pow.o \
  $(srcdir)/../libc/math/mipsel/e_rem_pio2.o \
  $(srcdir)/../libc/math/mipsel/e_remainder.o \
  $(srcdir)/../libc/math/mipsel/e_scalb.o \
  $(srcdir)/../libc/math/mipsel/e_sinh.o \
  $(srcdir)/../libc/math/mipsel/e_sqrt.o \
  $(srcdir)/../libc/math/mipsel/erfcf.o \
  $(srcdir)/../libc/math/mipsel/erff.o \
  $(srcdir)/../libc/math/mipsel/exp2f.o \
  $(srcdir)/../libc/math/mipsel/expf.o \
  $(srcdir)/../libc/math/mipsel/expm1f.o \
  $(srcdir)/../libc/math/mipsel/fabsf.o \
  $(srcdir)/../libc/math/mipsel/fdimf.o \
  $(srcdir)/../libc/math/mipsel/floorf.o \
  $(srcdir)/../libc/math/mipsel/fmaf.o \
  $(srcdir)/../libc/math/mipsel/fmaxf.o \
  $(srcdir)/../libc/math/mipsel/fminf.o \
  $(srcdir)/../libc/math/mipsel/fmodf.o \
  $(srcdir)/../libc/math/mipsel/frexpf.o \
  $(srcdir)/../libc/math/mipsel/hypotf.o \
  $(srcdir)/../libc/math/mipsel/ilogbf.o \
  $(srcdir)/../libc/math/mipsel/k_cos.o \
  $(srcdir)/../libc/math/mipsel/k_rem_pio2.o \
  $(srcdir)/../libc/math/mipsel/k_sin.o \
  $(srcdir)/../libc/math/mipsel/k_standard.o \
  $(srcdir)/../libc/math/mipsel/k_tan.o \
  $(srcdir)/../libc/math/mipsel/ldexpf.o \
  $(srcdir)/../libc/math/mipsel/lgammaf.o \
  $(srcdir)/../libc/math/mipsel/llrintf.o \
  $(srcdir)/../libc/math/mipsel/llroundf.o \
  $(srcdir)/../libc/math/mipsel/log10f.o \
  $(srcdir)/../libc/math/mipsel/log1pf.o \
  $(srcdir)/../libc/math/mipsel/log2f.o \
  $(srcdir)/../libc/math/mipsel/logbf.o \
  $(srcdir)/../libc/math/mipsel/logf.o \
  $(srcdir)/../libc/math/mipsel/lrintf.o \
  $(srcdir)/../libc/math/mipsel/lroundf.o \
  $(srcdir)/../libc/math/mipsel/modff.o \
  $(srcdir)/../libc/math/mipsel/nan.o \
  $(srcdir)/../libc/math/mipsel/nearbyintf.o \
  $(srcdir)/../libc/math/mipsel/nextafterf.o \
  $(srcdir)/../libc/math/mipsel/powf.o \
  $(srcdir)/../libc/math/mipsel/remainderf.o \
  $(srcdir)/../libc/math/mipsel/remquof.o \
  $(srcdir)/../libc/math/mipsel/rintf.o \
  $(srcdir)/../libc/math/mipsel/roundf.o \
  $(srcdir)/../libc/math/mipsel/s_asinh.o \
  $(srcdir)/../libc/math/mipsel/s_atan.o \
  $(srcdir)/../libc/math/mipsel/s_cbrt.o \
  $(srcdir)/../libc/math/mipsel/s_ceil.o \
  $(srcdir)/../libc/math/mipsel/s_copysign.o \
  $(srcdir)/../libc/math/mipsel/s_cos.o \
  $(srcdir)/../libc/math/mipsel/s_erf.o \
  $(srcdir)/../libc/math/mipsel/s_expm1.o \
  $(srcdir)/../libc/math/mipsel/s_fabs.o \
  $(srcdir)/../libc/math/mipsel/s_fdim.o \
  $(srcdir)/../libc/math/mipsel/s_finite.o \
  $(srcdir)/../libc/math/mipsel/s_finitef.o \
  $(srcdir)/../libc/math/mipsel/s_floor.o \
  $(srcdir)/../libc/math/mipsel/s_fma.o \
  $(srcdir)/../libc/math/mipsel/s_fmax.o \
  $(srcdir)/../libc/math/mipsel/s_fmin.o \
  $(srcdir)/../libc/math/mipsel/s_fpclassify.o \
  $(srcdir)/../libc/math/mipsel/s_fpclassifyf.o \
  $(srcdir)/../libc/math/mipsel/s_frexp.o \
  $(srcdir)/../libc/math/mipsel/s_ilogb.o \
  $(srcdir)/../libc/math/mipsel/s_isinf.o \
  $(srcdir)/../libc/math/mipsel/s_isinff.o \
  $(srcdir)/../libc/math/mipsel/s_isnan.o \
  $(srcdir)/../libc/math/mipsel/s_isnanf.o \
  $(srcdir)/../libc/math/mipsel/s_ldexp.o \
  $(srcdir)/../libc/math/mipsel/s_lib_version.o \
  $(srcdir)/../libc/math/mipsel/s_llrint.o \
  $(srcdir)/../libc/math/mipsel/s_llround.o \
  $(srcdir)/../libc/math/mipsel/s_log1p.o \
  $(srcdir)/../libc/math/mipsel/s_logb.o \
  $(srcdir)/../libc/math/mipsel/s_lrint.o \
  $(srcdir)/../libc/math/mipsel/s_lround.o \
  $(srcdir)/../libc/math/mipsel/s_matherr.o \
  $(srcdir)/../libc/math/mipsel/s_modf.o \
  $(srcdir)/../libc/math/mipsel/s_nearbyint.o \
  $(srcdir)/../libc/math/mipsel/s_nextafter.o \
  $(srcdir)/../libc/math/mipsel/s_remquo.o \
  $(srcdir)/../libc/math/mipsel/s_rint.o \
  $(srcdir)/../libc/math/mipsel/s_round.o \
  $(srcdir)/../libc/math/mipsel/s_scalbln.o \
  $(srcdir)/../libc/math/mipsel/s_scalbn.o \
  $(srcdir)/../libc/math/mipsel/s_signbit.o \
  $(srcdir)/../libc/math/mipsel/s_signbitf.o \
  $(srcdir)/../libc/math/mipsel/s_signgam.o \
  $(srcdir)/../libc/math/mipsel/s_significand.o \
  $(srcdir)/../libc/math/mipsel/s_sin.o \
  $(srcdir)/../libc/math/mipsel/s_tan.o \
  $(srcdir)/../libc/math/mipsel/s_tanh.o \
  $(srcdir)/../libc/math/mipsel/s_trunc.o \
  $(srcdir)/../libc/math/mipsel/scalblnf.o \
  $(srcdir)/../libc/math/mipsel/scalbnf.o \
  $(srcdir)/../libc/math/mipsel/sinf.o \
  $(srcdir)/../libc/math/mipsel/sinhf.o \
  $(srcdir)/../libc/math/mipsel/sqrtf.o \
  $(srcdir)/../libc/math/mipsel/tanf.o \
  $(srcdir)/../libc/math/mipsel/tanhf.o \
  $(srcdir)/../libc/math/mipsel/tgammaf.o \
  $(srcdir)/../libc/math/mipsel/truncf.o \
  $(srcdir)/../libc/math/mipsel/w_acos.o \
  $(srcdir)/../libc/math/mipsel/w_acosh.o \
  $(srcdir)/../libc/math/mipsel/w_asin.o \
  $(srcdir)/../libc/math/mipsel/w_atan2.o \
  $(srcdir)/../libc/math/mipsel/w_atanh.o \
  $(srcdir)/../libc/math/mipsel/w_cabs.o \
  $(srcdir)/../libc/math/mipsel/w_cosh.o \
  $(srcdir)/../libc/math/mipsel/w_drem.o \
  $(srcdir)/../libc/math/mipsel/w_exp.o \
  $(srcdir)/../libc/math/mipsel/w_exp2.o \
  $(srcdir)/../libc/math/mipsel/w_fmod.o \
  $(srcdir)/../libc/math/mipsel/w_gamma.o \
  $(srcdir)/../libc/math/mipsel/w_hypot.o \
  $(srcdir)/../libc/math/mipsel/w_j0.o \
  $(srcdir)/../libc/math/mipsel/w_j1.o \
  $(srcdir)/../libc/math/mipsel/w_jn.o \
  $(srcdir)/../libc/math/mipsel/w_lgamma.o \
  $(srcdir)/../libc/math/mipsel/w_lgamma_r.o \
  $(srcdir)/../libc/math/mipsel/w_log.o \
  $(srcdir)/../libc/math/mipsel/w_log10.o \
  $(srcdir)/../libc/math/mipsel/w_log2.o \
  $(srcdir)/../libc/math/mipsel/w_pow.o \
  $(srcdir)/../libc/math/mipsel/w_remainder.o \
  $(srcdir)/../libc/math/mipsel/w_sinh.o \
  $(srcdir)/../libc/math/mipsel/w_sqrt.o \
  $(srcdir)/../libc/math/mipsel/w_tgamma.o

EXTRA_DIST += $(MIPSELMATHOBJS)
