MTSMATHOBJS = \
  $(srcdir)/../libc/math/mtsparc/acosf.o \
  $(srcdir)/../libc/math/mtsparc/acoshf.o \
  $(srcdir)/../libc/math/mtsparc/asinf.o \
  $(srcdir)/../libc/math/mtsparc/asinhf.o \
  $(srcdir)/../libc/math/mtsparc/atan2f.o \
  $(srcdir)/../libc/math/mtsparc/atanf.o \
  $(srcdir)/../libc/math/mtsparc/atanhf.o \
  $(srcdir)/../libc/math/mtsparc/cabsf.o \
  $(srcdir)/../libc/math/mtsparc/carg.o \
  $(srcdir)/../libc/math/mtsparc/cargf.o \
  $(srcdir)/../libc/math/mtsparc/cbrtf.o \
  $(srcdir)/../libc/math/mtsparc/ceilf.o \
  $(srcdir)/../libc/math/mtsparc/copysignf.o \
  $(srcdir)/../libc/math/mtsparc/cosf.o \
  $(srcdir)/../libc/math/mtsparc/coshf.o \
  $(srcdir)/../libc/math/mtsparc/e_acos.o \
  $(srcdir)/../libc/math/mtsparc/e_acosh.o \
  $(srcdir)/../libc/math/mtsparc/e_asin.o \
  $(srcdir)/../libc/math/mtsparc/e_atan2.o \
  $(srcdir)/../libc/math/mtsparc/e_atanh.o \
  $(srcdir)/../libc/math/mtsparc/e_cosh.o \
  $(srcdir)/../libc/math/mtsparc/e_exp.o \
  $(srcdir)/../libc/math/mtsparc/e_fmod.o \
  $(srcdir)/../libc/math/mtsparc/e_gamma.o \
  $(srcdir)/../libc/math/mtsparc/e_gamma_r.o \
  $(srcdir)/../libc/math/mtsparc/e_hypot.o \
  $(srcdir)/../libc/math/mtsparc/e_j0.o \
  $(srcdir)/../libc/math/mtsparc/e_j1.o \
  $(srcdir)/../libc/math/mtsparc/e_jn.o \
  $(srcdir)/../libc/math/mtsparc/e_lgamma.o \
  $(srcdir)/../libc/math/mtsparc/e_lgamma_r.o \
  $(srcdir)/../libc/math/mtsparc/e_log.o \
  $(srcdir)/../libc/math/mtsparc/e_log10.o \
  $(srcdir)/../libc/math/mtsparc/e_log2.o \
  $(srcdir)/../libc/math/mtsparc/e_pow.o \
  $(srcdir)/../libc/math/mtsparc/e_rem_pio2.o \
  $(srcdir)/../libc/math/mtsparc/e_remainder.o \
  $(srcdir)/../libc/math/mtsparc/e_scalb.o \
  $(srcdir)/../libc/math/mtsparc/e_sinh.o \
  $(srcdir)/../libc/math/mtsparc/e_sqrt.o \
  $(srcdir)/../libc/math/mtsparc/erfcf.o \
  $(srcdir)/../libc/math/mtsparc/erff.o \
  $(srcdir)/../libc/math/mtsparc/exp2f.o \
  $(srcdir)/../libc/math/mtsparc/expf.o \
  $(srcdir)/../libc/math/mtsparc/expm1f.o \
  $(srcdir)/../libc/math/mtsparc/fabsf.o \
  $(srcdir)/../libc/math/mtsparc/fdimf.o \
  $(srcdir)/../libc/math/mtsparc/floorf.o \
  $(srcdir)/../libc/math/mtsparc/fmaf.o \
  $(srcdir)/../libc/math/mtsparc/fmaxf.o \
  $(srcdir)/../libc/math/mtsparc/fminf.o \
  $(srcdir)/../libc/math/mtsparc/fmodf.o \
  $(srcdir)/../libc/math/mtsparc/frexpf.o \
  $(srcdir)/../libc/math/mtsparc/hypotf.o \
  $(srcdir)/../libc/math/mtsparc/ilogbf.o \
  $(srcdir)/../libc/math/mtsparc/k_cos.o \
  $(srcdir)/../libc/math/mtsparc/k_rem_pio2.o \
  $(srcdir)/../libc/math/mtsparc/k_sin.o \
  $(srcdir)/../libc/math/mtsparc/k_standard.o \
  $(srcdir)/../libc/math/mtsparc/k_tan.o \
  $(srcdir)/../libc/math/mtsparc/ldexpf.o \
  $(srcdir)/../libc/math/mtsparc/lgammaf.o \
  $(srcdir)/../libc/math/mtsparc/llrintf.o \
  $(srcdir)/../libc/math/mtsparc/llroundf.o \
  $(srcdir)/../libc/math/mtsparc/log10f.o \
  $(srcdir)/../libc/math/mtsparc/log1pf.o \
  $(srcdir)/../libc/math/mtsparc/log2f.o \
  $(srcdir)/../libc/math/mtsparc/logbf.o \
  $(srcdir)/../libc/math/mtsparc/logf.o \
  $(srcdir)/../libc/math/mtsparc/lrintf.o \
  $(srcdir)/../libc/math/mtsparc/lroundf.o \
  $(srcdir)/../libc/math/mtsparc/modff.o \
  $(srcdir)/../libc/math/mtsparc/nan.o \
  $(srcdir)/../libc/math/mtsparc/nearbyintf.o \
  $(srcdir)/../libc/math/mtsparc/nextafterf.o \
  $(srcdir)/../libc/math/mtsparc/powf.o \
  $(srcdir)/../libc/math/mtsparc/remainderf.o \
  $(srcdir)/../libc/math/mtsparc/remquof.o \
  $(srcdir)/../libc/math/mtsparc/rintf.o \
  $(srcdir)/../libc/math/mtsparc/roundf.o \
  $(srcdir)/../libc/math/mtsparc/s_asinh.o \
  $(srcdir)/../libc/math/mtsparc/s_atan.o \
  $(srcdir)/../libc/math/mtsparc/s_cbrt.o \
  $(srcdir)/../libc/math/mtsparc/s_ceil.o \
  $(srcdir)/../libc/math/mtsparc/s_copysign.o \
  $(srcdir)/../libc/math/mtsparc/s_cos.o \
  $(srcdir)/../libc/math/mtsparc/s_erf.o \
  $(srcdir)/../libc/math/mtsparc/s_expm1.o \
  $(srcdir)/../libc/math/mtsparc/s_fabs.o \
  $(srcdir)/../libc/math/mtsparc/s_fdim.o \
  $(srcdir)/../libc/math/mtsparc/s_finite.o \
  $(srcdir)/../libc/math/mtsparc/s_finitef.o \
  $(srcdir)/../libc/math/mtsparc/s_floor.o \
  $(srcdir)/../libc/math/mtsparc/s_fma.o \
  $(srcdir)/../libc/math/mtsparc/s_fmax.o \
  $(srcdir)/../libc/math/mtsparc/s_fmin.o \
  $(srcdir)/../libc/math/mtsparc/s_fpclassify.o \
  $(srcdir)/../libc/math/mtsparc/s_fpclassifyf.o \
  $(srcdir)/../libc/math/mtsparc/s_frexp.o \
  $(srcdir)/../libc/math/mtsparc/s_ilogb.o \
  $(srcdir)/../libc/math/mtsparc/s_isinf.o \
  $(srcdir)/../libc/math/mtsparc/s_isinff.o \
  $(srcdir)/../libc/math/mtsparc/s_isnan.o \
  $(srcdir)/../libc/math/mtsparc/s_isnanf.o \
  $(srcdir)/../libc/math/mtsparc/s_ldexp.o \
  $(srcdir)/../libc/math/mtsparc/s_lib_version.o \
  $(srcdir)/../libc/math/mtsparc/s_llrint.o \
  $(srcdir)/../libc/math/mtsparc/s_llround.o \
  $(srcdir)/../libc/math/mtsparc/s_log1p.o \
  $(srcdir)/../libc/math/mtsparc/s_logb.o \
  $(srcdir)/../libc/math/mtsparc/s_lrint.o \
  $(srcdir)/../libc/math/mtsparc/s_lround.o \
  $(srcdir)/../libc/math/mtsparc/s_matherr.o \
  $(srcdir)/../libc/math/mtsparc/s_modf.o \
  $(srcdir)/../libc/math/mtsparc/s_nearbyint.o \
  $(srcdir)/../libc/math/mtsparc/s_nextafter.o \
  $(srcdir)/../libc/math/mtsparc/s_remquo.o \
  $(srcdir)/../libc/math/mtsparc/s_rint.o \
  $(srcdir)/../libc/math/mtsparc/s_round.o \
  $(srcdir)/../libc/math/mtsparc/s_scalbln.o \
  $(srcdir)/../libc/math/mtsparc/s_scalbn.o \
  $(srcdir)/../libc/math/mtsparc/s_signbit.o \
  $(srcdir)/../libc/math/mtsparc/s_signbitf.o \
  $(srcdir)/../libc/math/mtsparc/s_signgam.o \
  $(srcdir)/../libc/math/mtsparc/s_significand.o \
  $(srcdir)/../libc/math/mtsparc/s_sin.o \
  $(srcdir)/../libc/math/mtsparc/s_tan.o \
  $(srcdir)/../libc/math/mtsparc/s_tanh.o \
  $(srcdir)/../libc/math/mtsparc/s_trunc.o \
  $(srcdir)/../libc/math/mtsparc/scalblnf.o \
  $(srcdir)/../libc/math/mtsparc/scalbnf.o \
  $(srcdir)/../libc/math/mtsparc/sinf.o \
  $(srcdir)/../libc/math/mtsparc/sinhf.o \
  $(srcdir)/../libc/math/mtsparc/sqrtf.o \
  $(srcdir)/../libc/math/mtsparc/tanf.o \
  $(srcdir)/../libc/math/mtsparc/tanhf.o \
  $(srcdir)/../libc/math/mtsparc/tgammaf.o \
  $(srcdir)/../libc/math/mtsparc/truncf.o \
  $(srcdir)/../libc/math/mtsparc/w_acos.o \
  $(srcdir)/../libc/math/mtsparc/w_acosh.o \
  $(srcdir)/../libc/math/mtsparc/w_asin.o \
  $(srcdir)/../libc/math/mtsparc/w_atan2.o \
  $(srcdir)/../libc/math/mtsparc/w_atanh.o \
  $(srcdir)/../libc/math/mtsparc/w_cabs.o \
  $(srcdir)/../libc/math/mtsparc/w_cosh.o \
  $(srcdir)/../libc/math/mtsparc/w_drem.o \
  $(srcdir)/../libc/math/mtsparc/w_exp.o \
  $(srcdir)/../libc/math/mtsparc/w_exp2.o \
  $(srcdir)/../libc/math/mtsparc/w_fmod.o \
  $(srcdir)/../libc/math/mtsparc/w_gamma.o \
  $(srcdir)/../libc/math/mtsparc/w_hypot.o \
  $(srcdir)/../libc/math/mtsparc/w_j0.o \
  $(srcdir)/../libc/math/mtsparc/w_j1.o \
  $(srcdir)/../libc/math/mtsparc/w_jn.o \
  $(srcdir)/../libc/math/mtsparc/w_lgamma.o \
  $(srcdir)/../libc/math/mtsparc/w_lgamma_r.o \
  $(srcdir)/../libc/math/mtsparc/w_log.o \
  $(srcdir)/../libc/math/mtsparc/w_log10.o \
  $(srcdir)/../libc/math/mtsparc/w_log2.o \
  $(srcdir)/../libc/math/mtsparc/w_pow.o \
  $(srcdir)/../libc/math/mtsparc/w_remainder.o \
  $(srcdir)/../libc/math/mtsparc/w_sinh.o \
  $(srcdir)/../libc/math/mtsparc/w_sqrt.o \
  $(srcdir)/../libc/math/mtsparc/w_tgamma.o

EXTRA_DIST += $(MTSMATHOBJS)
