MTAMATHOBJS = \
$(srcdir)/../libc/math/mtalpha/m/acosf.o \
$(srcdir)/../libc/math/mtalpha/m/acoshf.o \
$(srcdir)/../libc/math/mtalpha/m/asinf.o \
$(srcdir)/../libc/math/mtalpha/m/asinhf.o \
$(srcdir)/../libc/math/mtalpha/m/atan2f.o \
$(srcdir)/../libc/math/mtalpha/m/atanf.o \
$(srcdir)/../libc/math/mtalpha/m/atanhf.o \
$(srcdir)/../libc/math/mtalpha/m/cabsf.o \
$(srcdir)/../libc/math/mtalpha/m/carg.o \
$(srcdir)/../libc/math/mtalpha/m/cargf.o \
$(srcdir)/../libc/math/mtalpha/m/cbrtf.o \
$(srcdir)/../libc/math/mtalpha/m/ceilf.o \
$(srcdir)/../libc/math/mtalpha/m/copysignf.o \
$(srcdir)/../libc/math/mtalpha/m/cosf.o \
$(srcdir)/../libc/math/mtalpha/m/coshf.o \
$(srcdir)/../libc/math/mtalpha/m/e_acos.o \
$(srcdir)/../libc/math/mtalpha/m/e_acosh.o \
$(srcdir)/../libc/math/mtalpha/m/e_asin.o \
$(srcdir)/../libc/math/mtalpha/m/e_atan2.o \
$(srcdir)/../libc/math/mtalpha/m/e_atanh.o \
$(srcdir)/../libc/math/mtalpha/m/e_cosh.o \
$(srcdir)/../libc/math/mtalpha/m/e_exp.o \
$(srcdir)/../libc/math/mtalpha/m/e_fmod.o \
$(srcdir)/../libc/math/mtalpha/m/e_gamma.o \
$(srcdir)/../libc/math/mtalpha/m/e_gamma_r.o \
$(srcdir)/../libc/math/mtalpha/m/e_hypot.o \
$(srcdir)/../libc/math/mtalpha/m/e_j0.o \
$(srcdir)/../libc/math/mtalpha/m/e_j1.o \
$(srcdir)/../libc/math/mtalpha/m/e_jn.o \
$(srcdir)/../libc/math/mtalpha/m/e_lgamma.o \
$(srcdir)/../libc/math/mtalpha/m/e_lgamma_r.o \
$(srcdir)/../libc/math/mtalpha/m/e_log.o \
$(srcdir)/../libc/math/mtalpha/m/e_log2.o \
$(srcdir)/../libc/math/mtalpha/m/e_log10.o \
$(srcdir)/../libc/math/mtalpha/m/e_pow.o \
$(srcdir)/../libc/math/mtalpha/m/e_rem_pio2.o \
$(srcdir)/../libc/math/mtalpha/m/e_remainder.o \
$(srcdir)/../libc/math/mtalpha/m/e_scalb.o \
$(srcdir)/../libc/math/mtalpha/m/e_sinh.o \
$(srcdir)/../libc/math/mtalpha/m/e_sqrt.o \
$(srcdir)/../libc/math/mtalpha/m/erfcf.o \
$(srcdir)/../libc/math/mtalpha/m/erff.o \
$(srcdir)/../libc/math/mtalpha/m/exp2f.o \
$(srcdir)/../libc/math/mtalpha/m/expf.o \
$(srcdir)/../libc/math/mtalpha/m/expm1f.o \
$(srcdir)/../libc/math/mtalpha/m/fabsf.o \
$(srcdir)/../libc/math/mtalpha/m/fdimf.o \
$(srcdir)/../libc/math/mtalpha/m/floorf.o \
$(srcdir)/../libc/math/mtalpha/m/fmaf.o \
$(srcdir)/../libc/math/mtalpha/m/fmaxf.o \
$(srcdir)/../libc/math/mtalpha/m/fminf.o \
$(srcdir)/../libc/math/mtalpha/m/fmodf.o \
$(srcdir)/../libc/math/mtalpha/m/frexpf.o \
$(srcdir)/../libc/math/mtalpha/m/hypotf.o \
$(srcdir)/../libc/math/mtalpha/m/ilogbf.o \
$(srcdir)/../libc/math/mtalpha/m/k_cos.o \
$(srcdir)/../libc/math/mtalpha/m/k_rem_pio2.o \
$(srcdir)/../libc/math/mtalpha/m/k_sin.o \
$(srcdir)/../libc/math/mtalpha/m/k_standard.o \
$(srcdir)/../libc/math/mtalpha/m/k_tan.o \
$(srcdir)/../libc/math/mtalpha/m/ldexpf.o \
$(srcdir)/../libc/math/mtalpha/m/lgammaf.o \
$(srcdir)/../libc/math/mtalpha/m/llrintf.o \
$(srcdir)/../libc/math/mtalpha/m/llroundf.o \
$(srcdir)/../libc/math/mtalpha/m/log1pf.o \
$(srcdir)/../libc/math/mtalpha/m/log2f.o \
$(srcdir)/../libc/math/mtalpha/m/log10f.o \
$(srcdir)/../libc/math/mtalpha/m/logbf.o \
$(srcdir)/../libc/math/mtalpha/m/logf.o \
$(srcdir)/../libc/math/mtalpha/m/lrintf.o \
$(srcdir)/../libc/math/mtalpha/m/lroundf.o \
$(srcdir)/../libc/math/mtalpha/m/modff.o \
$(srcdir)/../libc/math/mtalpha/m/nan.o \
$(srcdir)/../libc/math/mtalpha/m/nearbyintf.o \
$(srcdir)/../libc/math/mtalpha/m/nextafterf.o \
$(srcdir)/../libc/math/mtalpha/m/powf.o \
$(srcdir)/../libc/math/mtalpha/m/remainderf.o \
$(srcdir)/../libc/math/mtalpha/m/remquof.o \
$(srcdir)/../libc/math/mtalpha/m/rintf.o \
$(srcdir)/../libc/math/mtalpha/m/roundf.o \
$(srcdir)/../libc/math/mtalpha/m/s_asinh.o \
$(srcdir)/../libc/math/mtalpha/m/s_atan.o \
$(srcdir)/../libc/math/mtalpha/m/s_cbrt.o \
$(srcdir)/../libc/math/mtalpha/m/s_ceil.o \
$(srcdir)/../libc/math/mtalpha/m/s_copysign.o \
$(srcdir)/../libc/math/mtalpha/m/s_cos.o \
$(srcdir)/../libc/math/mtalpha/m/s_erf.o \
$(srcdir)/../libc/math/mtalpha/m/s_expm1.o \
$(srcdir)/../libc/math/mtalpha/m/s_fabs.o \
$(srcdir)/../libc/math/mtalpha/m/s_fdim.o \
$(srcdir)/../libc/math/mtalpha/m/s_finite.o \
$(srcdir)/../libc/math/mtalpha/m/s_finitef.o \
$(srcdir)/../libc/math/mtalpha/m/s_floor.o \
$(srcdir)/../libc/math/mtalpha/m/s_fma.o \
$(srcdir)/../libc/math/mtalpha/m/s_fmax.o \
$(srcdir)/../libc/math/mtalpha/m/s_fmin.o \
$(srcdir)/../libc/math/mtalpha/m/s_fpclassify.o \
$(srcdir)/../libc/math/mtalpha/m/s_fpclassifyf.o \
$(srcdir)/../libc/math/mtalpha/m/s_frexp.o \
$(srcdir)/../libc/math/mtalpha/m/s_ilogb.o \
$(srcdir)/../libc/math/mtalpha/m/s_isinf.o \
$(srcdir)/../libc/math/mtalpha/m/s_isinff.o \
$(srcdir)/../libc/math/mtalpha/m/s_isnan.o \
$(srcdir)/../libc/math/mtalpha/m/s_isnanf.o \
$(srcdir)/../libc/math/mtalpha/m/s_ldexp.o \
$(srcdir)/../libc/math/mtalpha/m/s_lib_version.o \
$(srcdir)/../libc/math/mtalpha/m/s_llrint.o \
$(srcdir)/../libc/math/mtalpha/m/s_llround.o \
$(srcdir)/../libc/math/mtalpha/m/s_log1p.o \
$(srcdir)/../libc/math/mtalpha/m/s_logb.o \
$(srcdir)/../libc/math/mtalpha/m/s_lrint.o \
$(srcdir)/../libc/math/mtalpha/m/s_lround.o \
$(srcdir)/../libc/math/mtalpha/m/s_matherr.o \
$(srcdir)/../libc/math/mtalpha/m/s_modf.o \
$(srcdir)/../libc/math/mtalpha/m/s_nearbyint.o \
$(srcdir)/../libc/math/mtalpha/m/s_nextafter.o \
$(srcdir)/../libc/math/mtalpha/m/s_remquo.o \
$(srcdir)/../libc/math/mtalpha/m/s_rint.o \
$(srcdir)/../libc/math/mtalpha/m/s_round.o \
$(srcdir)/../libc/math/mtalpha/m/s_scalbln.o \
$(srcdir)/../libc/math/mtalpha/m/s_scalbn.o \
$(srcdir)/../libc/math/mtalpha/m/s_signbit.o \
$(srcdir)/../libc/math/mtalpha/m/s_signbitf.o \
$(srcdir)/../libc/math/mtalpha/m/s_signgam.o \
$(srcdir)/../libc/math/mtalpha/m/s_significand.o \
$(srcdir)/../libc/math/mtalpha/m/s_sin.o \
$(srcdir)/../libc/math/mtalpha/m/s_tan.o \
$(srcdir)/../libc/math/mtalpha/m/s_tanh.o \
$(srcdir)/../libc/math/mtalpha/m/s_trunc.o \
$(srcdir)/../libc/math/mtalpha/m/scalblnf.o \
$(srcdir)/../libc/math/mtalpha/m/scalbnf.o \
$(srcdir)/../libc/math/mtalpha/m/sinf.o \
$(srcdir)/../libc/math/mtalpha/m/sinhf.o \
$(srcdir)/../libc/math/mtalpha/m/sqrtf.o \
$(srcdir)/../libc/math/mtalpha/m/tanf.o \
$(srcdir)/../libc/math/mtalpha/m/tanhf.o \
$(srcdir)/../libc/math/mtalpha/m/tgammaf.o \
$(srcdir)/../libc/math/mtalpha/m/truncf.o \
$(srcdir)/../libc/math/mtalpha/m/w_acos.o \
$(srcdir)/../libc/math/mtalpha/m/w_acosh.o \
$(srcdir)/../libc/math/mtalpha/m/w_asin.o \
$(srcdir)/../libc/math/mtalpha/m/w_atan2.o \
$(srcdir)/../libc/math/mtalpha/m/w_atanh.o \
$(srcdir)/../libc/math/mtalpha/m/w_cabs.o \
$(srcdir)/../libc/math/mtalpha/m/w_cosh.o \
$(srcdir)/../libc/math/mtalpha/m/w_drem.o \
$(srcdir)/../libc/math/mtalpha/m/w_exp.o \
$(srcdir)/../libc/math/mtalpha/m/w_exp2.o \
$(srcdir)/../libc/math/mtalpha/m/w_fmod.o \
$(srcdir)/../libc/math/mtalpha/m/w_gamma.o \
$(srcdir)/../libc/math/mtalpha/m/w_hypot.o \
$(srcdir)/../libc/math/mtalpha/m/w_j0.o \
$(srcdir)/../libc/math/mtalpha/m/w_j1.o \
$(srcdir)/../libc/math/mtalpha/m/w_jn.o \
$(srcdir)/../libc/math/mtalpha/m/w_lgamma.o \
$(srcdir)/../libc/math/mtalpha/m/w_lgamma_r.o \
$(srcdir)/../libc/math/mtalpha/m/w_log.o \
$(srcdir)/../libc/math/mtalpha/m/w_log2.o \
$(srcdir)/../libc/math/mtalpha/m/w_log10.o \
$(srcdir)/../libc/math/mtalpha/m/w_pow.o \
$(srcdir)/../libc/math/mtalpha/m/w_remainder.o \
$(srcdir)/../libc/math/mtalpha/m/w_sinh.o \
$(srcdir)/../libc/math/mtalpha/m/w_sqrt.o \
$(srcdir)/../libc/math/mtalpha/m/w_tgamma.o 

EXTRA_DIST += $(MTAMATHOBJS)
